unit_test:
  is_url_conn: true
  exchange: "amq.direct"
  queue: "TEST::NEW"
  durable: True
  prefetch:
    count: 1
dev:
  is_url_conn: true
  exchange: "amq.direct"
  queue: "logger"
  durable: True
  prefetch:
    count: 1
