unit_test:
  is_url_conn: true
  exchange:
    name: "amq"
    type: "direct"
  queue: "TEST::NEW"
  routing_key: "TEST::NEW"
  durable: True
  prefetch:
    count: 1
dev:
  is_url_conn: true
  exchange:
    name: "amq"
    type: "direct"
  queue: "logger"
  routing_key: "logger"
  durable: True
  prefetch:
    count: 1
